# ==============================================================================
# S3 Bucket for Application Static Assets
# ==============================================================================
# Stores static media, CSS, JavaScript, and asset uploads served via CloudFront CDN.
resource "aws_s3_bucket" "static_assets" {
  bucket        = "restaurant-api-${var.environment}-static-assets-${data.aws_caller_identity.current.account_id}"
  force_destroy = var.environment == "dev" ? true : false

  # checkov:skip=CKV2_AWS_62:S3 event notifications are disabled on the static assets bucket because it exclusively stores static assets with no event-driven downstream consumers.
  # checkov:skip=CKV_AWS_144:Cross-Region Replication is disabled for the static assets bucket to prevent redundant storage costs and inter-region data transfer fees; static assets can be easily redeployed via CI/CD pipelines if a regional disaster occurs.
  # checkov:skip=CKV_AWS_145:KMS encryption is bypassed for the static assets bucket to eliminate unnecessary KMS key baseline costs and API transaction fees; standard default S3-managed encryption (SSE-S3) is sufficient and secure at rest.
  # checkov:skip=CKV_AWS_18:Server access logging is disabled on the static assets bucket to prevent storage bloating and high-volume PUT request billing generated by internal CI/CD processes.

  # Restrict tags strictly to Name; provider default_tags handle environment and project metadata
  tags = {
    Name = "restaurant-api-${var.environment}-static-assets"
  }
}


# ==============================================================================
# S3 Server-Side Encryption Configuration
# ==============================================================================
# Enforces AES256 server-side encryption (SSE-S3) for all stored objects at rest.
resource "aws_s3_bucket_server_side_encryption_configuration" "static_assets" {
  bucket = aws_s3_bucket.static_assets.id

  # checkov:skip=CKV_AWS_145:KMS encryption is bypassed for the static assets bucket to eliminate unnecessary KMS key baseline costs and API transaction fees; standard default S3-managed encryption (SSE-S3) is sufficient and secure at rest.

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}


# ==============================================================================
# S3 Public Access Block Configuration
# ==============================================================================
# Blocks direct public S3 internet traffic. Access is granted strictly to CloudFront
# via Origin Access Control (OAC) in the ingress module.
resource "aws_s3_bucket_public_access_block" "static_assets" {
  bucket                  = aws_s3_bucket.static_assets.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}


# ==============================================================================
# S3 CORS Configuration
# ==============================================================================
# Configures Cross-Origin Resource Sharing (CORS) rules to allow client browsers
# to fetch static media assets seamlessly.
resource "aws_s3_bucket_cors_configuration" "static_assets" {
  bucket = aws_s3_bucket.static_assets.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "HEAD"]
    allowed_origins = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}


# ==============================================================================
# S3 Bucket Versioning Configuration
# ==============================================================================
# Retains object versioning history for backup retention and state rollback capability.
resource "aws_s3_bucket_versioning" "static_assets" {
  bucket = aws_s3_bucket.static_assets.id

  versioning_configuration {
    status = "Enabled"
  }
}

# ===============================================================================
# FINOPS LIFECYCLE CONFIGURATION (Automated Storage Cost Mitigation)
# =============================================================================
resource "aws_s3_bucket_lifecycle_configuration" "static_assets_lifecycle" {
  bucket = aws_s3_bucket.static_assets.id

  rule {
    id     = "cleanup_historical_deployments_and_ghost_costs"
    status = "Enabled"

    # Optimization 1: Clean up incomplete multipart uploads after 7 days.
    # Prevents "ghost storage" fees if a CI/CD network blip breaks an upload halfway through.
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }

    # Optimization 2: Zero-Trust Rollback Retention Policy
    # Keep the active version forever, but clean up older deployment history.
    noncurrent_version_expiration {
      noncurrent_days           = 30 # Delete old versions once they've been inactive for 30 days
      newer_noncurrent_versions = 3  # CRITICAL: Always keep the last 3 historical versions for emergency rollbacks!
    }
  }
}