# ESO fetches the RDS password and Django Secret Key from AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secrets.storeName }}   # Name of the ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-app-secrets # The actual K8s Secret created by ESO
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.awsSecretName }}  # The name of the secret in AWS Secrets Manager